Update generate-geoip-geosite.yml

diff --git a/.github/workflows/generate-geoip-geosite.yml b/.github/workflows/generate-geoip-geosite.yml
--- a/.github/workflows/generate-geoip-geosite.yml
+++ b/.github/workflows/generate-geoip-geosite.yml
@@ -13,13 +13,14 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         
       - name: Pull Changes
         run: git pull
 
       - name: Set up Node.js (if required)
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
+        
         with:
           node-version: '20'  # Adjust if needed
 
@@ -31,7 +32,7 @@ jobs:
       - name: Download generate-geoip-geosite
         run: |
           DOWNLOAD_URL=$(curl -s https://api.github.com/repos/Dunamis4tw/generate-geoip-geosite/releases/latest | grep "generate-geoip-geosite.*linux-amd64.tar.gz" | grep "browser_download_url" | cut -d '"' -f 4)
-          wget "$DOWNLOAD_URL"
+          wget "$DOWNLOAD_URL" || exit 1  # Exit if download fails
 
       - name: Extract generate-geoip-geosite
         run: |
@@ -92,7 +93,7 @@ jobs:
           add: '*.srs'
           author_name: GitHub Action
           author_email: githubaction@githubaction.com
-          message: 'Update AdAway and Torrents Lists ${{ steps.date.outputs.date }}'
+          message: 'Update AdAway and Torrents Lists ${{ steps.date.outputs.date }}'  # Add date variable
           push: true
           cwd: .
           default_author: github_actor
